[package]
name = "hello-world-desktop-2"
version = "0.1.0"
description = "AI Gang Tauri desktop template"
authors = ["AI Gang"]
edition = "2021"

[lib]
name = "hello_world_desktop_2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
